query allPosts {
  posts {
    uuid
    title
    body
    comments {
      uuid
      text
    }
  }
}

query singlePost($uuid: ID!) {
  post(uuid: $uuid) {
    uuid
    title
    body
    comments {
      uuid
      text
    }
  }
}
